name: KBOT-CICD

on:
  push:
    branches:  
    - 'develop'

env:
  TARGETARCH: amd64
  
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
                          
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run test
        run: make test; 
        
      - name: Run login
        run: echo ${{ secrets.ghp_for_dockerhub }} | docker login ghcr.io -u ivanloktionov --password-stdin
     
      - name: Build&Push
        env:
          APP: "kbot"
          REGISTRY: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.ghp_for_dockerhub }}
        run: make image push 
      - name: Clean
        run: make clean
      
  cd:
    name: CD
    needs: ci
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - run: echo "VERSION=$(git describe --tags --abbrev=0)-$(git rev-parse --short HEAD)" >> $GITHUB_ENV
    

    - uses: mikefarah/yq@master
      with:
        cmd: yq -i '.image.tag=strenv(VERSION) | .image.arch=strenv(TARGETARCH)' helm/values.yaml
    - run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git pull
        git commit -am "update version $VERSION"
        git push
